### ISSUE TITLE
sync data replace local data

### ISSUE THREAD

**Issue by bikram109** [immortalsantee/SyncEngine#1]
At offline condition app run fine but when there is internet and app get sync the locally saved data are replaced from old server data

**Comment by immortalsantee** [comment]
Make sure you set sync_status = {1,2 or 3} before calling SyncEngine method.
Note:
1 = create
2 = delete
3 = update

Note: 
-Make sure you have got all data that is greater the given updated_at date in your request. Most probably your issue might be because of response datas sent from server. 
Check your response updated_at with the one you sent in parameter and you will find issue.

Thanks
